src/Entity/User.php
<?php

namespace App\Entity;

use ArrayAccess;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\Email(message = "L'email '{{ value }}' n'est pas valide !")
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=3, max=255, minMessage = "Votre prénom doit faire au minimum {{ limit }} caractères")
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=2, max=255, minMessage = "Votre nom doit faire au minimum {{ limit }} caractères")
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=6, max=255, minMessage = "Votre adresse doit faire au minimum {{ limit }} caractères")
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min = 10, max = 10, minMessage = "Numéro invalide", maxMessage = "Numéro invalide")
     * @Assert\Regex(pattern="/^[0-9]*$/", message="un numéro de téléphone ne peut contenir que des chiffres")
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $civility;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex(pattern="/^[0-9]*$/", message="un code postal ne peut contenir que des chiffres")
     * @Assert\Length(min = 5, max = 5, minMessage = "code postal invalide", maxMessage = "code postal invalide")
     */
    private $zipCode;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min = 3, minMessage = "Votre Pays n'existe pas")
     */
    private $country;

    /**
     * @ORM\Column(type="date")
     */
    private $birthday;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cerfaFilename;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $taxStampDeliverance;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $taxStampInnerWater;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $identityFilename;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $identityPictureFilename;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $taxStampCoastal;

    /**
     * @ORM\Column(type="boolean")
     */
    private $IsActivated;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getCivility(): ?string
    {
        return $this->civility;
    }

    public function setCivility(string $civility): self
    {
        $this->civility = $civility;

        return $this;
    }

    public function getZipCode(): ?string
    {
        return $this->zipCode;
    }

    public function setZipCode(string $zipCode): self
    {
        $this->zipCode = $zipCode;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getCerfaFilename(): ?string
    {
        return $this->cerfaFilename;
    }

    public function setCerfaFilename(?string $cerfaFilename): self
    {
        $this->cerfaFilename = $cerfaFilename;

        return $this;
    }

    public function getTaxStampDeliverance(): ?string
    {
        return $this->taxStampDeliverance;
    }

    public function setTaxStampDeliverance(?string $taxStampDeliverance): self
    {
        $this->taxStampDeliverance = $taxStampDeliverance;

        return $this;
    }

    public function getTaxStampInnerWater(): ?string
    {
        return $this->taxStampInnerWater;
    }

    public function setTaxStampInnerWater(?string $taxStampInnerWater): self
    {
        $this->taxStampInnerWater = $taxStampInnerWater;

        return $this;
    }

    public function getIdentityFilename(): ?string
    {
        return $this->identityFilename;
    }

    public function setIdentityFilename(?string $identityFilename): self
    {
        $this->identityFilename = $identityFilename;

        return $this;
    }

    public function getIdentityPictureFilename(): ?string
    {
        return $this->identityPictureFilename;
    }

    public function setIdentityPictureFilename(?string $identityPictureFilename): self
    {
        $this->identityPictureFilename = $identityPictureFilename;

        return $this;
    }

    public function getTaxStampCoastal(): ?string
    {
        return $this->taxStampCoastal;
    }

    public function setTaxStampCoastal(?string $taxStampCoastal): self
    {
        $this->taxStampCoastal = $taxStampCoastal;

        return $this;
    }

    public function getIsActivated(): ?bool
    {
        return $this->IsActivated;
    }

    public function setIsActivated(bool $IsActivated): self
    {
        $this->IsActivated = $IsActivated;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content={% block metadescription %}{% endblock %} />
    <title>Bateau École Pilote{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/png" href="https://zupimages.net/up/21/04/2zj1.png" />
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet">
    <link rel="icon" type="image/png" href="https://zupimages.net/up/21/04/2zj1.png" />
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Oxygen&family=Roboto:wght@700&display=swap" rel="stylesheet">
    {{ encore_entry_link_tags('app') }}
    {% block stylesheets %}
    {% endblock %}
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg primary-color nav-cart">
            <a class="navbar-brand" href="{{ path('home')}}"><img class="logo-nav"
                    src="https://zupimages.net/up/21/04/2zj1.png" alt="navbar logo">
            </a>
            <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon fixed-top ml-auto"><i class="fas fa-bars"></i></span>
            </button>
            <div class="collapse navbar-collapse" id="basicExampleNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link " href="{{ path('home')}}">Accueil
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('license_index') }}">Formation</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('contact')}}">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('blog')}}">Blog</a>
                    </li>
                    {% if is_granted("ROLE_ADMIN") %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('admin')}}">Admin</a>
                    </li>
                    {% endif %}
                    {% if is_granted("ROLE_USER")%}
                    {% if app.user.isActivated == 1 %}
                    {% if not is_granted("ROLE_ADMIN")%}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('profile') }}">Profil</a>
                    </li>
                    {% endif %}
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('app_logout')}}"><i class="fas fa-sign-out-alt"></i></a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('app_login')}}">Connexion</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        {% if is_granted("ROLE_USER")%}
        {% if app.user.isActivated == 0 %}
        <div class="alert alert-success" role="alert">
            Merci de vérifier vos mails pour activer votre compte (pensez à regarder le dossier spam) !
        </div>
        {% endif %}
        {% endif %}
        <div class="menu">
            <nav class="menu__nav">
                <ul class="menu__list r-list">
                    <li class="menu__group">
                        <a class="menu__link r-link " href="{{ path('home')}}">Accueil
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="menu__group">
                        <a class="menu__link r-link" href="{{ path('license_index') }}">Formation</a>
                    </li>
                    <li class="menu__group">
                        <a class="menu__link r-link" href="{{ path('contact')}}">Contact</a>
                    </li>
                    <li class="menu__group">
                        <a class="menu__link r-link" href="{{ path('blog')}}">Blog</a>
                    </li>
                    {% if is_granted("ROLE_ADMIN") %}
                    <li class="menu__group">
                        <a class="menu__link r-link" href="{{ path('admin')}}">Admin</a>
                    </li>
                    {% endif %}
                    {% if is_granted("ROLE_USER")%}
                    {% if app.user.isActivated == 1 %}
                    {% if not is_granted("ROLE_ADMIN")%}
                    <li class="menu__group">
                        <a class="menu__link r-link" href="{{ path('profile') }}">Profil</a>
                    </li>
                    {% endif %}
                    {% endif %}
                    <li class="menu__group">
                        <a class="menu__link r-link" href="{{ path('app_logout')}}"><i
                                class="fas fa-sign-out-alt"></i></a>
                    </li>
                    {% else %}
                    <li class="menu__group">
                        <a class="menu__link r-link" href="{{ path('app_login')}}">Connexion</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            <button class="menu__toggle r-button" type="button">
                <span class="menu__hamburger m-hamburger">
                    <span class="m-hamburger__label">
                        <span class="menu__screen-reader screen-reader">Open menu</span>
                    </span>
                </span>
            </button>
        </div>
    </header>
    {% block body %}{% endblock %}
    <footer class="footer footer-bg d-none d-lg-block pb-4">
        <div class="container justify-fluid-content-around">
            <div class="row align-items-center">
                <div class="col-lg-4 text-center">
                    <div class="col-md-12">
                        <a class="footer-brand" href="{{ path('home')}}"><img class="logo-footer"
                                src="https://zupimages.net/up/21/04/2zj1.png" alt="navbar logo">
                            <div class="container-fluid">
                                <a class="space" href="tel:{{ info.infoFooter[0].phone}}"><img
                                        src="https://zupimages.net/up/20/51/td5h.png" class="reseau-footer"
                                        alt="logo-phone"></a>
                                <a class="space" href="mailto:{{ info.infoFooter[0].mail }}"><img
                                        src="https://zupimages.net/up/20/51/yvjh.png" class="reseau-footer"
                                        alt="logo-mail"></a>
                            </div>
                    </div>
                </div>
                <div class="col-lg-4 mt-4 text-center">
                    <h3 class="pt-3 information-style">Informations</h3>
                    <hr class="hr-color">
                    <div class="row">
                        <div class="col-md-12">
                            <a class="footer-information" href="{{ path('contact')}}">Contact</a>
                            <br>
                            <a class="footer-information" href="{{ path('faq')}}">Faq</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 text-center">
                    <h3 class="pt-3 information-style">Nous suivre</h3>
                    <hr class="hr-color">
                    <div class="row">
                        <div class="col-md-12">
                            <a class="space" href="https://www.facebook.com/ecoledeconduite.pilote.3"><img
                                    src="https://zupimages.net/up/20/51/lxhz.png" class="reseau-footer"
                                    alt="logo-facebook"></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div style="height: 50px"></div>
    </footer>
    <script src="https://kit.fontawesome.com/eacfbebdea.js" crossorigin="anonymous"></script>
    {{ encore_entry_script_tags('app') }}
    {% block javascripts %}
    {% endblock %}
</body>

</html>